'use client';

import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';

export default function TermsPage() {
  return (
    <div style={{ minHeight: '100vh', background: '#f8fafc' }}>
      <div style={{ maxWidth: 800, margin: '0 auto', padding: '40px 24px 80px' }}>
        <Link
          href="/login"
          style={{
            display: 'inline-flex',
            alignItems: 'center',
            gap: 6,
            color: '#3b82f6',
            textDecoration: 'none',
            fontSize: 14,
            marginBottom: 24,
          }}
        >
          <ArrowLeft size={16} />
          Back to Login
        </Link>

        <h1 style={{ fontSize: 28, fontWeight: 700, color: '#0f172a', marginBottom: 4 }}>
          Terms &amp; Conditions
        </h1>
        <p style={{ fontSize: 13, color: '#94a3b8', marginBottom: 32 }}>
          Last Updated: July 15, 2026
        </p>

        <div style={{ display: 'flex', flexDirection: 'column', gap: 28, color: '#334155', fontSize: 14, lineHeight: 1.7 }}>
          <section>
            <p>
              This document is an electronic record in terms of the Information Technology Act, 2000
              and rules thereunder as applicable and the amended provisions pertaining to electronic
              records in various statutes as amended by the Information Technology Act, 2000. This
              electronic record is generated by a computer system and does not require any physical
              or digital signatures.
            </p>
          </section>

          <section>
            <p>
              Kriscel Tech Private Limited, a private limited company incorporated under the laws of
              India (&quot;Company&quot;, &quot;we&quot;, &quot;us&quot; or &quot;our&quot;), manages
              and operates the TaskEasy platform, including the website, domain name, and any other
              linked pages, features, content, mobile application, or any other services we offer
              from time to time in connection therewith (collectively the &quot;Platform&quot;) which
              is an online platform that enables users to manage tasks, projects, team collaboration,
              and provide effective task management for organizations (collectively, the
              &quot;Services&quot;).
            </p>
          </section>

          <section>
            <p>
              All users of the Platform are advised to read and understand our Privacy Policy and
              Terms &amp; Conditions carefully before registering, accessing or using the Platform or
              any services offered by the Company. By giving your consent for accessing the Platform
              (either as a visitor or a customer), you (hereinafter referred to as &quot;you&quot;,
              &quot;your&quot;, &quot;user&quot;, as applicable) expressly consent to our collection,
              storage, use and disclosure of information shared by you with the Company in accordance
              with the terms of these Terms and Conditions and the Privacy Policy, as amended from
              time to time.
            </p>
          </section>

          <section>
            <p>
              We reserve the right, at our sole discretion, to change, modify, add or remove
              portions of these terms, at any time without any prior written notice to you. By
              accessing, browsing, or otherwise using the Platform, including following the posting
              of changes, the user agrees to accept and be bound by the terms (as may be amended
              from time to time). It is your responsibility to review these terms periodically for
              any updates/changes.
            </p>
          </section>

          <section>
            <h2 style={{ fontSize: 18, fontWeight: 600, color: '#0f172a', marginBottom: 10 }}>
              1. Application
            </h2>
            <p>
              The Platform is a web-based platform that offers the Services subject to these Terms as
              well as the Privacy Policy and any other rules and policies of the Platform that the
              Company may publish from time to time. You must read the Company&apos;s Privacy Policy
              which governs the collection, use, and disclosure of personal information about users.
              You accept the terms of the Privacy Policy and agree to the use of the personal
              information about you in accordance with the Privacy Policy.
            </p>
          </section>

          <section>
            <h2 style={{ fontSize: 18, fontWeight: 600, color: '#0f172a', marginBottom: 10 }}>
              2. Subscription &amp; Registration
            </h2>
            <p>
              It is mandatory to register or subscribe to access and use the Platform. You need to
              register, subscribe and create one or more user accounts (each an
              &quot;Account&quot;) to avail such Services on the Platform by providing your name,
              email address, password, and other details as required. By registering and creating
              your Account on the Platform, you agree to:
            </p>
            <ul style={{ paddingLeft: 20, marginTop: 8 }}>
              <li>Provide accurate, current and complete information and maintain and update the same;</li>
              <li>Maintain the security of your password;</li>
              <li>Accept all risks of unauthorized access to the Registration Data;</li>
              <li>Notify us immediately of any breach of security or any unauthorized use of your Account;</li>
              <li>Be responsible for all activity on your Account and to use and operate the same in accordance with applicable law.</li>
            </ul>
            <p style={{ marginTop: 10 }}>
              We reserve the right to disallow, cancel, remove or reassign certain usernames in
              appropriate circumstances, and may suspend or terminate your Account if activities
              occur on that Account which would or might constitute a violation of these Terms.
            </p>
          </section>

          <section>
            <h2 style={{ fontSize: 18, fontWeight: 600, color: '#0f172a', marginBottom: 10 }}>
              3. Eligibility
            </h2>
            <p>
              The Platform is available for use and access to users who can form legally binding
              contracts under the Indian Contract Act, 1872. Users must be at least 18 years of age
              to access and use the Platform.
            </p>
          </section>

          <section>
            <h2 style={{ fontSize: 18, fontWeight: 600, color: '#0f172a', marginBottom: 10 }}>
              4. User Obligations
            </h2>
            <p>You agree that:</p>
            <ul style={{ paddingLeft: 20, marginTop: 8 }}>
              <li>You will not copy, reproduce, download, sell, distribute or resell any Services or Platform content;</li>
              <li>You will not use the Platform content for the purposes of operating a competing business;</li>
              <li>You will not undertake any action which may undermine the integrity of the Platform;</li>
              <li>You are fully able and competent to understand and agree to these Terms;</li>
              <li>You will use the Platform and Services only for lawfully permitted purposes;</li>
              <li>You shall comply with all applicable laws while using the Platform.</li>
            </ul>
          </section>

          <section>
            <h2 style={{ fontSize: 18, fontWeight: 600, color: '#0f172a', marginBottom: 10 }}>
              5. Intellectual Property Rights
            </h2>
            <p>
              The Company is the sole owner or lawful licensee of all the rights and interests in the
              Platform and the Platform Content. All title, ownership and intellectual property rights
              in the Platform and Platform Content shall remain with the Company. The unauthorized
              copying, modification, use or publication of the &quot;TaskEasy&quot; brand and any
              related icons and logos is strictly prohibited.
            </p>
          </section>

          <section>
            <h2 style={{ fontSize: 18, fontWeight: 600, color: '#0f172a', marginBottom: 10 }}>
              6. Breaches &amp; Suspension
            </h2>
            <p>
              If any user breaches any Terms, or if the Company has reasonable grounds to believe a
              user is in breach, the Company shall have the right to take disciplinary actions
              including suspending or terminating the user&apos;s account, blocking or restricting
              access to Services, and removing user content.
            </p>
          </section>

          <section>
            <h2 style={{ fontSize: 18, fontWeight: 600, color: '#0f172a', marginBottom: 10 }}>
              7. Payment of Fees
            </h2>
            <p>
              The Company shall have sole discretion to charge fees on Services provided by it
              through the Platform in accordance with its internal policies. The Company will not be
              responsible for any fraudulent use of the services.
            </p>
          </section>

          <section>
            <h2 style={{ fontSize: 18, fontWeight: 600, color: '#0f172a', marginBottom: 10 }}>
              8. Indemnification
            </h2>
            <p>
              By accepting these Terms and using the Platform, you agree that you shall defend,
              indemnify and hold the Company, its directors, employees, shareholders, officers and
              other representatives harmless from and against any and all claims, costs, damages,
              losses, liabilities and expenses arising out of or in connection with: misuse of the
              Platform; your violation or breach of these Terms or any applicable law; your violation
              of any rights of any third party; or any third-party claims based upon your usage.
            </p>
          </section>

          <section>
            <h2 style={{ fontSize: 18, fontWeight: 600, color: '#0f172a', marginBottom: 10 }}>
              9. Limitation of Liability
            </h2>
            <p>
              To the maximum extent permitted by law, the Services provided by the Company are
              provided &quot;as is&quot;, &quot;as available&quot; and &quot;with all faults&quot;.
              Under no circumstances will the Company be liable for any consequential, incidental,
              special, exemplary or punitive damages, including but not limited to any lost profits
              that result from your use of this Platform.
            </p>
          </section>

          <section>
            <h2 style={{ fontSize: 18, fontWeight: 600, color: '#0f172a', marginBottom: 10 }}>
              10. Force Majeure
            </h2>
            <p>
              Under no circumstances shall the Company be held liable for any losses, delay or
              failure or disruption of the content or services resulting directly or indirectly from
              acts of nature, forces or causes beyond our reasonable control, including without
              limitation, internet failures, equipment failures, strikes, fires, floods, storms,
              acts of God, war, governmental actions, epidemics, pandemics, or non-performance of
              third parties.
            </p>
          </section>

          <section>
            <h2 style={{ fontSize: 18, fontWeight: 600, color: '#0f172a', marginBottom: 10 }}>
              11. Grievance Redressal
            </h2>
            <p>
              If there are any questions regarding these Terms, please write to the Grievance
              Officer. Any complaints or concerns shall be immediately informed to the designated
              Grievance Officer. The Grievance Officer shall acknowledge the complaint within 72
              hours and redress the complaints within 15 days from the date of receipt.
            </p>
            <div style={{ background: '#f1f5f9', borderRadius: 8, padding: 16, marginTop: 12 }}>
              <p style={{ margin: 0, fontWeight: 600 }}>Grievance Officer</p>
              <p style={{ margin: '4px 0 0' }}>Kriscel Tech Pvt. Ltd.</p>
              <p style={{ margin: '4px 0 0' }}>Phone: +91 8985419420</p>
              <p style={{ margin: '4px 0 0' }}>Email: Info@kriscel.com</p>
            </div>
          </section>

          <section>
            <h2 style={{ fontSize: 18, fontWeight: 600, color: '#0f172a', marginBottom: 10 }}>
              12. Jurisdiction
            </h2>
            <p>
              Any kind of dispute arising out of the Platform and its users will be dealt in India
              and shall be governed in accordance with Indian Law. If for any reason, any part of the
              provision of these Terms is deemed invalid, the remaining which is valid will be put to
              use.
            </p>
          </section>
        </div>

        <footer style={{
          marginTop: 48,
          paddingTop: 24,
          borderTop: '1px solid #e2e8f0',
          fontSize: 12,
          color: '#94a3b8',
          textAlign: 'center',
        }}>
          COPYRIGHT &copy; 2026 &ndash; Kriscel Tech Pvt. Ltd., India
        </footer>
      </div>
    </div>
  );
}
